version: 2

jobs:

  build:
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build --no-cache -t lowieh/name-com-slave-dns:latest .
      - deploy:
          name: Push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push lowieh/name-com-slave-dns:latest
            fi


workflows:
  version: 2

  build:
    jobs:
      - build
